{% set version = "1.2.3" %}

package:
  name: throttler
  version: {{ version }}

source:
  url: https://github.com/uburuntu/throttler/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3bdf235ed8eb70d68b900bdc35daa854fd5981c298f8de0fb848a42d61f78774

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - throttler
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uburuntu/throttler
  summary: Easy throttling with asyncio support
  description: |
    Zero-dependency Python package for easy throttling with asyncio support.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/uburuntu/throttler
  dev_url: https://github.com/uburuntu/throttler

extra:
  recipe-maintainers:
    - johanneskoester
